name: spectral
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.0
  - scikit-learn
  - numpy
  - scipy
  - pytest
  - pytest-cov
  - umap-learn
  - matplotlib
  - jupyter
